apiVersion: apps/v1
kind: Deployment
metadata:
  name: kyma-test
  labels:
    app: kyma-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kyma-test
  template:
    metadata:
      labels:
        app: kyma-test
    spec:
      containers:
      - name: kyma-test
        image: ghcr.io/sunilchandra007/sap-community-code-challenge-cloud-native:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
            limits:
              ephemeral-storage: 256M
              memory: 256M
              cpu: 100m
            requests:
              cpu: 100m
              ephemeral-storage: 256M
              memory: 256M
      imagePullSecrets:
      - name: regcred
status: {}
      
---
apiVersion: v1
kind: Service
metadata:
  name: kyma-test
spec:
  selector:
    app: kyma-test
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP

---

apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: kyma-test
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: kyma-test
    port: 8080
    host: kyma-test
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
          config: {}